---
title: "Welcome"
# output: html_notebook
---

This is the welcome page to the audition exercise, so welcome!

For this body of work, I have captured both the development cycle and deployment of the results within the same r workflow, using an rproject + rmarkdown files to organize my work (version controlled within a github repo) and then deployed this website via netlify.

Please click on the different sections above to navigate to those respective bodies of work. 

Thank you so much for your time!  
-phil

<br>

# Section Overview  

__1. R: Top 50 Analysis__

* In this section, the goal was to show my analysis of the csv provided (top_50.csv)  
* The code in this section is meant to be able to be hidden and shown as desired, so the reviewer can see my thought process.

__2. R: Precision/Recall__    

* This section, I utilized a dataset from the "tidyTuesday" repository and simplified the problem to create a first pass of a classification model.  
* It is off this model that I ran precision/recall/accuracy metrics on the test split.  


__3. SQL: Transactions__  

* In this section, I will work through the work problem of the SQL example. 
* I built some sample tables, which I believed would behave in a similar fashion to that of what was described.  
* In the subsequent sections, I then added and ran the SQL code that I believe addressed the question at hand (with a sample of the output included below).



# Notes

* This site is currently hosted for free using the netlify app. __[https://spacee-audition.netlify.app]__. It is currently connected to the repo which houses the site as well as the analysis steps __[https://github.com/phildwalker/SpaceeAudition]__
    * Please let me know if you would like for me to take the site down (while I don't have any internet followers, I'm not sure if there are any concerns around the exercise surfacing on the internet).

* I am very grateful for both the abundance of resources online to help provide the documentation to quickly get this site deployed via netlify, as well as my former coworkers at Cone Health who have helped me to grow in my R knowledge as well as helping to show me how to integrate the css/html portions to take the results to another level.

